# Generated by Django 2.2.24 on 2022-03-26 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='dark_mode',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='langue',
            field=models.CharField(choices=[('fr', 'Français'), ('ar', 'Arabic')], default='fr', max_length=10),
        ),
    ]
