# Generated by Django 2.2.24 on 2022-03-18 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0002_produit_categorie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='code_barre',
            field=models.CharField(blank=True, max_length=250, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='produit',
            name='reference',
            field=models.CharField(blank=True, max_length=250, null=True, unique=True),
        ),
    ]
