# Generated by Django 2.2.24 on 2022-03-26 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0003_auto_20220318_1332'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='code_barre_lower',
            field=models.CharField(blank=True, editable=False, max_length=250, null=True, unique=True),
        ),
    ]
